config/routes.rb
LoyalBlocks::Application.routes.draw do
  get "deals/index"
	resources :deals do
    collection do
      post 'update_recruitment_offer'
			post 'update_slow_hour_offer'
		end
	end

   root :to => 'deals#index'

end

app/models/recruitment_offer.rb
class RecruitmentOffer < ActiveRecord::Base
end

app/models/slow_hour_offer.rb
class SlowHourOffer < ActiveRecord::Base
	Times = ["00:00", "01:00", "02:00", "03:00","04:00", "05:00", "06:00", "07:00","08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00","17:00", "18:00", "19:00", "20:00","21:00", "22:00", "23:00"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  def index
		@recruitment_offer = RecruitmentOffer.first
		@recruitment_offer_text = @recruitment_offer ? @recruitment_offer.description : "“A Convict Cordial, our special soda”"
		@slow_hour_offer = SlowHourOffer.first
		@slow_hour_offer = SlowHourOffer.new(:description => "“A Convict Cordial, our special soda”") if @slow_hour_offer.nil?
  end

	def update_recruitment_offer
		recruitment_offer = RecruitmentOffer.first
		recruitment_offer = RecruitmentOffer.new if recruitment_offer.nil?
		recruitment_offer.description = params[:description]
		recruitment_offer.save
		respond_to do |format|  
			format.html { redirect_to(deals_path) }  
			format.js   { render :nothing => true }  
		end 
	end
	
	def update_slow_hour_offer
		slow_hour_offer = SlowHourOffer.first
		slow_hour_offer = SlowHourOffer.create if slow_hour_offer.nil?
		slow_hour_offer.update_attributes(params[:slow_hour_offer])
		respond_to do |format|  
			format.html { redirect_to(deals_path) }  
			format.js   { render :nothing => true }  
		end 
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_bring_a_friend_container.html.erb
<div class="box">
	<a href="#" class="arrow">arrow</a>
	<%= image_tag "ico-03.png", :width => "60", :height => "59", :alt => "image description" %>
	<div class="text-holder">
		<h2>Bring a friend</h2>
		<p>To enable automatic check-ins for your customers, you need an android device. It doesn't matter if it's a phone or a tablet, as long as it stays in the store </p>
	</div>
</div>

app/views/deals/_facebook_connect_container.html.erb
<div class="box">
	<a href="#" class="arrow">arrow</a>
	<%= image_tag "ico-04.png", :width => "60", :height => "59", :alt => "image description" %>
	<div class="text-holder">
		<h2>“Connect with Facebook” offer</h2>
		<p>To enable automatic check-ins for your customers, you need an android device. It doesn't matter if it's a phone or a tablet, as long as it stays in the store </p>
	</div>
</div>

app/views/deals/_geo_offer_container.html.erb
<div class="box">
	<a href="#" class="arrow">arrow</a>
	<%= image_tag "ico-06.png", :width => "60", :height => "59", :alt => "image description" %>
	<div class="text-holder">
		<h2>Geo Fence Offer</h2>
		<p>To enable automatic check-ins for your customers, you need an android device. It doesn't matter if it's a phone or a tablet, as long as it stays in the store </p>  
	</div>
</div>

app/views/deals/_lucky_customer_container.html.erb
<div class="box">
	<a href="#" class="arrow">arrow</a>
	<%= image_tag "ico-07.png", :width => "60", :height => "59", :alt => "image description" %>
	<div class="text-holder">
		<h2>Lucky Customer</h2>
		<p>To enable automatic check-ins for your customers, you need an android device. It doesn't matter if it's a phone or a tablet, as long as it stays in the store </p>
	</div>
</div>

app/views/deals/_recruitment_offer_container.html.erb
<div class="box">
	<a href="#" class="arrow">arrow</a>
	<%= image_tag "ico-01.png", :width => "60", :height => "59", :alt => "image description" %>
	<div class="text-holder">
		<h2>Recruitment Offer</h2>
		<p>Offer new customers a deal that will make them join </p>
	</div>
</div>
<div class="content">
	<div class="block">
		<div class="holder">
			<div class="frame">
				<%= form_tag update_recruitment_offer_deals_path, :remote => true, :method => :post, :class=> "form-offer", :id => 'recruitment_offer_form' do %>
					<fieldset>
						<div class="text-field-1">
							<%= image_tag asset_path('ajax_spinner.gif'), :id=> 'recruitment_spinner' %>
							<%= image_tag asset_path('green_ticket.png'), :id=> 'recruitment_success' %>
							<input type="text" value="<%= @recruitment_offer_text %>" name="description">
						</div>
						<input type="image" src="<%= asset_path 'btn-publish.gif' %>" alt="publish">
					</fieldset>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/deals/_regular_offer_container.html.erb
<div class="box">
	<a href="#" class="arrow">arrow</a>
	<%= image_tag "ico-05.png", :width => "60", :height => "59", :alt => "image description" %>
	<div class="text-holder">
		<h2>Regular’s Offer</h2>
		<p>o enable automatic check-ins for your customers, you need an android device. It doesn't matter if it's a phone or a tablet, as long as it stays in the store </p>
	</div>
</div>

app/views/deals/_slow_hour_offer_container.html.erb
<div class="box">
	<a href="#" class="arrow">arrow</a>
	<%= image_tag "ico-02.png", :width => "60", :height => "59", :alt => "image description" %>
	<div class="text-holder">
		<h2>Slow Hours</h2>
		<p>Give a special reward between your slow hours. <br> i.e: “A Convict Cordial” between 2:00 pm and 4:00 pm </p>
	</div>
</div>
<div class="content">
	<div class="block">
		<div class="holder">
			<div class="frame">
			<%= form_for(@slow_hour_offer, :url => update_slow_hour_offer_deals_path, :method => :post, :remote => true, :html => { :class => "form-hours", :id => "slow_hour_offer_form" }) do |f| %>
					<fieldset>
						<div class="row">
							<div class="col">
								<strong>When are your slow hours?</strong>
								<div class="select-holder">
									<%= f.select "start_time", options_for_select(SlowHourOffer::Times, @slow_hour_offer.start_time), {}, :class => "time" %>
									<span class="text">to</span>
									<%= f.select "end_time", options_for_select(SlowHourOffer::Times, @slow_hour_offer.end_time), {}, :class => "time" %>
								</div>
							</div>
							<div class="col">
								<strong>What days are your slow hours?</strong>
								<ul class="week-list">
									<li <%= @slow_hour_offer.monday? ? "class='on'" : nil %>>
										<a href="#" class="mon">mon</a>
										<%= f.check_box "monday", :hidden => true %>
									</li>
									<li <%= @slow_hour_offer.tuesday? ? "class='on'" : nil %>>
										<a href="#" class="tue">tue</a>
										<%= f.check_box "tuesday", :hidden => true %>
									</li>
									<li <%= @slow_hour_offer.wednesday? ? "class='on'" : nil %>>
										<a href="#" class="wed">wed</a>
										<%= f.check_box "wednesday", :hidden => true %>
									</li>
									<li <%= @slow_hour_offer.thursday? ? "class='on'" : nil %>>
										<a href="#" class="thu">thu</a>
										<%= f.check_box "thursday", :hidden => true %>
									</li>
									<li <%= @slow_hour_offer.friday? ? "class='on'" : nil %>>
										<a href="#" class="fri">fri</a>
										<%= f.check_box "friday", :hidden => true %>
									</li>
									<li <%= @slow_hour_offer.saturday? ? "class='on'" : nil %>>
										<a href="#" class="sat">sat</a>
										<%= f.check_box "saturday", :hidden => true %>
									</li>
									<li <%= @slow_hour_offer.sunday? ? "class='on'" : nil %>>
										<a href="#" class="sun">sun</a>
										<%= f.check_box "sunday", :hidden => true %>
									</li>
								</ul>
							</div>
						</div>
						<div class="row">
							<div class="text-box">
								<strong>Whats the offer?</strong>
								<input type="checkbox" id="facebook">
								<label for="facebook">Post on Facebook</label>
							</div>
							<div class="input-holder">
								<div class="text-field-2">
									<%= image_tag asset_path('ajax_spinner.gif'), :id=> 'slow_hour_spinner'%>
									<%= image_tag asset_path('green_ticket.png'), :id=> 'slow_hour_success' %>
									<%= f.text_field "description" %>
								</div>
								<input type="submit" value="submit" class="submit">
							</div>
						</div>
					</fieldset>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/deals/index.html.erb
<ul class="social">
	<li>
		<%= render :partial => "recruitment_offer_container" %>
	</li>
	<li>
		<%= render :partial => "slow_hour_offer_container" %>
	</li>
	<li>
		<%= render :partial => "bring_a_friend_container" %>
	</li>
	<li>
		<%= render :partial => "facebook_connect_container" %>
	</li>
	<li>
		<%= render :partial => "regular_offer_container" %>
	</li>
	<li>
		<%= render :partial => "geo_offer_container" %>
	</li>
	<li>
		<%= render :partial => "lucky_customer_container" %>
	</li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LoyalBlocks</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/deals.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>LoyalBlocks.net</title>
	<%= stylesheet_link_tag "application" %>
	<%= stylesheet_link_tag "all" %>
	<%= stylesheet_link_tag "form" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<link media="all" rel="stylesheet" href="css/all.css">
	<link media="all" rel="stylesheet" href="css/form.css">
	<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="css/ie.css" media="screen"/><![endif]-->
</head>
<body class="inner-page5">
	<div id="wrapper">
		<h1> Welcome to LoyalBlocks <br> Offer different deals to different customers.</h1>
		<div class="info">
			<p>To enable automatic check-ins for your customers, you need an android device. It doesn't matter if it's a phone or a tablet, as long as it stays in the store</p>
		</div>
		<%= yield %>
	</div>
</body>
</html>